# Generated by Django 5.1 on 2024-09-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_ponguser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponguser',
            name='password2',
            field=models.CharField(default='vivaPacman', max_length=250),
        ),
    ]
