# Generated by Django 5.1 on 2024-09-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_ponguser_online_status_matchhistory_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponguser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
