# Generated by Django 5.1 on 2024-11-28 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_ponguser_fortytwo_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_players', models.PositiveIntegerField(default=4)),
                ('custom_one', models.BooleanField(default=False)),
                ('custom_two', models.BooleanField(default=False)),
                ('custom_three', models.BooleanField(default=False)),
                ('custom_is_saved', models.BooleanField(default=False)),
                ('winner', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='tournament_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_id', to='users.tournament'),
        ),
    ]
